package com.eurobuddha.maxima.app;

import android.content.Context;
import android.content.SharedPreferences;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.util.Base64;

import com.eurobuddha.maxima.core.identity.Bip39;
import com.eurobuddha.maxima.core.identity.MaximaIdentity;

import java.nio.charset.StandardCharsets;
import java.security.KeyStore;
import java.util.List;

import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

/**
 * The seed phrase, stored as what it actually is: WALLET-GRADE MATERIAL.
 *
 * The phrase we generate is a real Minima seed phrase. That is deliberate -
 * installing Minima Core later and restoring with the same words reproduces
 * this exact Maxima identity, so contacts are never orphaned. But it also means
 * anyone holding this phrase can restore a wallet and spend anything ever sent
 * to it.
 *
 * So it is encrypted with an Android Keystore key rather than left in plain
 * SharedPreferences. Note the tradeoff, which apks/wallet SeedVault documents:
 * a Keystore key is device-bound and does NOT survive a restore to a new phone.
 * That is acceptable here precisely because the user has the WORDS - the phrase
 * is the portable backup, the Keystore copy is only the on-device convenience.
 *
 * There is no checksum in Minima's own generator, so we generate a STANDARD
 * checksummed BIP39 phrase (which Minima accepts, since it never validates a
 * checksum) and can therefore catch a mistyped restore.
 */
public final class SeedStore {

    private static final String PREFS = "maxima_identity";
    private static final String KEY_PHRASE = "phrase_enc";
    private static final String KEY_IV = "phrase_iv";
    private static final String KEY_NAME = "display_name";
    private static final String KEYSTORE_ALIAS = "maxima_seed_key";

    private SeedStore() {
    }

    public static boolean hasIdentity(Context zCtx) {
        return prefs(zCtx).contains(KEY_PHRASE);
    }

    public static String displayName(Context zCtx) {
        return prefs(zCtx).getString(KEY_NAME, "maxima");
    }

    public static void setDisplayName(Context zCtx, String zName) {
        prefs(zCtx).edit().putString(KEY_NAME, zName).apply();
    }

    /** Load the existing identity, or {@code null} if none has been created yet.
     *  NEVER mints. This is what the service uses on startup so that a fresh
     *  install can be gated behind onboarding (create-new vs restore) instead of
     *  silently generating an identity the user never gets to write down. */
    public static MaximaIdentity loadIdentity(Context zCtx) {
        String phrase = loadPhrase(zCtx);
        return phrase == null ? null : MaximaIdentity.fromPhrase(phrase);
    }

    /** Generate and save a brand-new identity.
     *  FUND-CRITICAL: unsynchronized, two callers could both see no phrase on a
     *  fresh install, each generate a DIFFERENT 24-word seed, and the last writer
     *  wins - any funds sent to the loser's derived address are unrecoverable. The
     *  whole check-generate-save is serialized, and the phrase is re-read after
     *  acquiring the lock so the second caller adopts the first's seed instead of
     *  minting its own. */
    public static synchronized MaximaIdentity createNewIdentity(Context zCtx) {
        String phrase = loadPhrase(zCtx);
        if (phrase == null) {
            List<String> words = Bip39.generate(24);
            phrase = String.join(" ", words);
            savePhrase(zCtx, phrase);
        }
        return MaximaIdentity.fromPhrase(phrase);
    }

    /** Load the existing identity, or generate one on first run. Thin shim kept
     *  for callers that must never be left without an identity (wallet
     *  canonicalSeed, jar migration) - they only run once onboarding has already
     *  established one, so this never mints unexpectedly. */
    public static synchronized MaximaIdentity loadOrCreateIdentity(Context zCtx) {
        MaximaIdentity id = loadIdentity(zCtx);
        return id != null ? id : createNewIdentity(zCtx);
    }

    /**
     * Import an existing phrase.
     *
     * The checksum is a WARNING, never a rejection: a phrase generated by
     * Minima's own {@code getNewWordList()} picks 24 words independently and
     * has no valid checksum, yet it is perfectly legitimate.
     */
    public static final class ImportResult {
        public final MaximaIdentity identity;
        public final boolean checksumValid;

        ImportResult(MaximaIdentity zIdentity, boolean zChecksum) {
            identity = zIdentity;
            checksumValid = zChecksum;
        }
    }

    public static ImportResult importPhrase(Context zCtx, String zPhrase) {
        // Throws on an unknown word, exactly as a Minima node would.
        String canonical = Bip39.cleanSeedPhrase(zPhrase);
        boolean checksum = Bip39.checksumValid(
                java.util.Arrays.asList(canonical.toLowerCase().split(" ")));
        savePhrase(zCtx, canonical);
        return new ImportResult(MaximaIdentity.fromPhrase(canonical), checksum);
    }

    /** Reveal the phrase for backup. Gate this behind biometric in the UI. */
    public static String revealPhrase(Context zCtx) {
        return loadPhrase(zCtx);
    }

    // ---------------------------------------------------------------

    private static SharedPreferences prefs(Context zCtx) {
        return zCtx.getSharedPreferences(PREFS, Context.MODE_PRIVATE);
    }

    private static void savePhrase(Context zCtx, String zPhrase) {
        try {
            SecretKey key = keystoreKey();
            Cipher c = Cipher.getInstance("AES/GCM/NoPadding");
            c.init(Cipher.ENCRYPT_MODE, key);
            byte[] ct = c.doFinal(zPhrase.getBytes(StandardCharsets.UTF_8));
            prefs(zCtx).edit()
                    .putString(KEY_PHRASE, Base64.encodeToString(ct, Base64.NO_WRAP))
                    .putString(KEY_IV, Base64.encodeToString(c.getIV(), Base64.NO_WRAP))
                    .apply();
        } catch (Exception e) {
            throw new IllegalStateException("Could not store seed securely", e);
        }
    }

    private static String loadPhrase(Context zCtx) {
        SharedPreferences p = prefs(zCtx);
        String ct = p.getString(KEY_PHRASE, null);
        String iv = p.getString(KEY_IV, null);
        if (ct == null || iv == null) {
            return null;
        }
        try {
            SecretKey key = keystoreKey();
            Cipher c = Cipher.getInstance("AES/GCM/NoPadding");
            c.init(Cipher.DECRYPT_MODE, key,
                    new GCMParameterSpec(128, Base64.decode(iv, Base64.NO_WRAP)));
            return new String(c.doFinal(Base64.decode(ct, Base64.NO_WRAP)),
                    StandardCharsets.UTF_8);
        } catch (Exception e) {
            throw new IllegalStateException("Could not read the stored seed", e);
        }
    }

    private static SecretKey keystoreKey() throws Exception {
        KeyStore ks = KeyStore.getInstance("AndroidKeyStore");
        ks.load(null);
        if (ks.containsAlias(KEYSTORE_ALIAS)) {
            return (SecretKey) ks.getKey(KEYSTORE_ALIAS, null);
        }
        KeyGenerator kg = KeyGenerator.getInstance(
                KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore");
        kg.init(new KeyGenParameterSpec.Builder(KEYSTORE_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT)
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .build());
        return kg.generateKey();
    }
}
