package com.eurobuddha.maxima.files;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/** Bounded preflight check before Bt's decoder, which allocates declared string lengths.
 * Only the small single-file format generated by Parlons is accepted. Unknown extensions
 * (including trackers and web seeds) and duplicate dictionary keys are rejected. */
final class BoundedMetadata {
    private final byte[] bytes;
    private int position;
    private BoundedMetadata(byte[] bytes) { this.bytes = bytes; }
    static void check(byte[] bytes) throws IOException {
        if (bytes.length == 0 || bytes.length > 24576) throw invalid();
        BoundedMetadata reader = new BoundedMetadata(bytes);
        reader.dictionary(false);
        if (reader.position != bytes.length) throw invalid();
    }
    private void dictionary(boolean info) throws IOException {
        expect('d');
        Set<String> allowed = new HashSet<>(Arrays.asList(info
                ? new String[]{"name", "length", "pieces", "piece length", "private"}
                : new String[]{"info", "created by", "creation date"}));
        Set<String> seen = new HashSet<>();
        while (peek() != 'e') {
            int length = stringLength();
            if (length > 32) throw invalid();
            String key = new String(bytes, position, length, StandardCharsets.US_ASCII);
            position += length;
            if (!allowed.contains(key) || !seen.add(key)) throw invalid();
            if ("info".equals(key)) dictionary(true);
            else if ("name".equals(key) || "pieces".equals(key) || "created by".equals(key))
                { int valueLength = stringLength(); position += valueLength; }
            else integer();
        }
        expect('e');
        if (info ? !seen.containsAll(allowed) : !seen.contains("info")) throw invalid();
    }
    private int stringLength() throws IOException {
        int length = 0, digits = 0;
        while (peek() != ':') {
            int c = peek();
            if (c < '0' || c > '9' || ++digits > 5 || (digits > 1 && length == 0)) throw invalid();
            length = length * 10 + c - '0'; position++;
        }
        expect(':');
        if (digits == 0 || length > bytes.length - position) throw invalid();
        return length;
    }
    private void integer() throws IOException {
        expect('i');
        int digits = 0; long value = 0;
        while (peek() != 'e') {
            int c = peek();
            if (c < '0' || c > '9' || ++digits > 12 || (digits > 1 && value == 0)) throw invalid();
            value = value * 10 + c - '0'; position++;
        }
        if (digits == 0) throw invalid();
        expect('e');
    }
    private int peek() throws IOException {
        if (position >= bytes.length) throw invalid();
        return bytes[position] & 255;
    }
    private void expect(int c) throws IOException { if (peek() != c) throw invalid(); position++; }
    private static IOException invalid() { return new IOException("Invalid private transfer metadata"); }
}
